MSDB/Controllers/BudgetsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MSDB;

namespace MSDB.Controllers
{
    public class BudgetsController : Controller
    {
        private readonly callme6lackContext _context;

        public BudgetsController(callme6lackContext context)
        {
            _context = context;
        }

        // GET: Budgets
        public async Task<IActionResult> Index()
        {
            return View(await _context.Budget.ToListAsync());
        }

        // GET: Budgets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget
                .FirstOrDefaultAsync(m => m.Id == id);
            if (budget == null)
            {
                return NotFound();
            }

            return View(budget);
        }

        // GET: Budgets/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Budgets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,SumBudget,Procent,Bonus")] Budget budget)
        {
            if (ModelState.IsValid)
            {
                _context.Database.ExecuteSqlRaw($"InsertBudgets @SumBudgets={budget.SumBudget},@Prosent={budget.Procent},@Bonus={budget.Bonus}");
                return RedirectToAction(nameof(Index));
            }
            return View(budget);
        }

        // GET: Budgets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {/*
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget.FindAsync(id);
            if (budget == null)
            {
                return NotFound();
            }*/
            var budget = _context.Budget.FromSqlInterpolated($"SelectIDBudgets @ID={id}").ToList();
            Budget budget1 = new Budget();
            foreach(var val in budget)
            {
                budget1.Id = val.Id;
                budget1.SumBudget = val.SumBudget;
                budget1.Procent = val.Procent;
                budget1.Bonus = val.Bonus;
            }
            return View(budget1);
        }

        // POST: Budgets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,SumBudget,Procent,Bonus")] Budget budget)
        {
            if (id != budget.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Database.ExecuteSqlRaw($"UpdateBudgets @ID={id}, @SumBudgets={budget.SumBudget},@Prosent={budget.Procent},@Bonus={budget.Bonus}");
                return RedirectToAction(nameof(Index));
                /*
                try
                {
                    _context.Update(budget);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BudgetExists(budget.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
                */
            }
            return View(budget);
        }

        // GET: Budgets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            /*
            if (id == null)
            {
                return NotFound();
            }

            var budget = await _context.Budget
                .FirstOrDefaultAsync(m => m.Id == id);
            if (budget == null)
            {
                return NotFound();
            }

            return View(budget);
            */
            var budget = _context.Budget.FromSqlInterpolated($"SelectIDBudgets @ID={id}").ToList();
            Budget budget1 = new Budget();
            foreach(var val in budget)
            {
                budget1.Id = val.Id;
                budget1.SumBudget = val.SumBudget;
                budget1.Procent = val.Procent;
                budget1.Bonus = val.Bonus;
            }
            return View(budget1);
        }

        // POST: Budgets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            callme6lackContext callme6LackContext = new callme6lackContext();
            callme6LackContext.Database.ExecuteSqlInterpolated($"DeleteBudgets @ID={id}");
            return RedirectToAction(nameof(Index));
        }
    }
}

MSDB/Controllers/UnitsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MSDB;

namespace MSDB.Controllers
{
    public class UnitsController : Controller
    {
        private readonly callme6lackContext _context;

        public UnitsController(callme6lackContext context)
        {
            _context = context;
        }

        // GET: Units
        public async Task<IActionResult> Index()
        {
            return View(await _context.Units.ToListAsync());
        }

        // GET: Units/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var units = await _context.Units
                .FirstOrDefaultAsync(m => m.Id == id);
            if (units == null)
            {
                return NotFound();
            }

            return View(units);
        }

        // GET: Units/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Units/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Unit")] Units units)
        {
            if (ModelState.IsValid)
            {
                _context.Add(units);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(units);
        }

        // GET: Units/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var units = await _context.Units.FindAsync(id);
            if (units == null)
            {
                return NotFound();
            }
            return View(units);
        }

        // POST: Units/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Unit")] Units units)
        {
            if (id != units.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(units);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UnitsExists(units.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(units);
        }

        // GET: Units/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var units = await _context.Units
                .FirstOrDefaultAsync(m => m.Id == id);
            if (units == null)
            {
                return NotFound();
            }

            return View(units);
        }

        // POST: Units/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var units = await _context.Units.FindAsync(id);
            _context.Units.Remove(units);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UnitsExists(int id)
        {
            return _context.Units.Any(e => e.Id == id);
        }
    }
}

MSDB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Производство</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;400&display=swap" rel="stylesheet">
</head>
<body>
    <header class="d-flex justify-content-center py-3">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-muted border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand text-black-50" asp-area="" asp-controller="Home" asp-action="Index">Производство</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Budgets" asp-action="Index">Бюджет</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Positions" asp-action="Index">Должности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Salaryes" asp-action="Index">Зарплата</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="BuyRawMaterials" asp-action="Index">Сырье</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Ingredients" asp-action="Index">Ингредиенты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="FinishedProducts" asp-action="Index">Продукция</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="PurchaseOfRawMaterials" asp-action="Index">Закупка</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="SaleOfProducts" asp-action="Index">Продажа</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Produtions" asp-action="Index">Производство</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-black" asp-area="" asp-controller="Units" asp-action="Index">Единица Измерения</a>
                        </li>
                    </ul>
                </div>
            </div>
</nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MSDB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>