MSDB/Models/Salaryes.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MSDB.Models
{
    public partial class Salaryes
    {
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int? Employee { get; set; }
        public short ParticipationInThePurchase { get; set; }
        public short ParticipationOnSale { get; set; }
        public short ParticipationOnProduction { get; set; }
        public int TotalNumberOfParticipations { get; set; }
        public decimal Bonus { get; set; }
        public float Salary { get; set; }
        public float TotalSum { get; set; }
        public bool Boolean { get; set; }

        public virtual Employees EmployeeNavigation { get; set; }
        public virtual Years Year_NameNavigation { get; set; }
        public virtual Months MonthNavigation { get; set; }
    }
}

MSDB/Controllers/SalaryesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using MSDB;
using MSDB.Models;

namespace MSDB.Controllers
{
    public class SalaryesController : Controller
    {
        float SumSalary = 0;
        private readonly callme6lackContext _context;

        public SalaryesController(callme6lackContext context)
        {
            _context = context;
        }

        // GET: Salaryes
        public async Task<IActionResult> Index(int yearstring, int monthstring, string M, int sum)
        {
            ViewData["Yea"] = new SelectList(_context.Years, "Year_Name", "Year_Name");
            ViewData["Month"] = new SelectList(_context.Months, "Id", "Month_Name");
            callme6lackContext db = new callme6lackContext();
            Employees employees = new Employees();
            var FP = db.Employees.FromSqlInterpolated($"SelectEmployee").ToList(); 
            // Запрос на хранимую процедуру для взятия количества записей
            List<Employees> employees1 = new List<Employees>();

            int i = 0;
            while (FP.Count > i)
            // Цикл от выше взятой записи
            {
                // Запись в модель
                employees1.Add(new Employees()
                {
                    Id = Convert.ToInt32(FP[i].Id),
                    Fio = FP[i].Fio.ToString()
                });
                i++;
            }

            Years years = new Years();
            var YE = db.Years.FromSqlInterpolated($"SelectAllYears").ToList();
            // Запрос на хранимую процедуру для взятия количества записей
            List<Years> years1 = new List<Years>();

            int k = 0;
            while (YE.Count > k)
            // Цикл от выше взятой записи
            {
                // Запись в модель
                years1.Add(new Years()
                {
                    Year_Name=Convert.ToInt32(YE[k].Year_Name)
                });
                k++;
            }

            Months months = new Months();
            var MO = db.Months.FromSqlInterpolated($"SelectAllMonth").ToList();
            // Запрос на хранимую процедуру для взятия количества записей
            List<Months> months1 = new List<Months>();

            int m = 0;
            while (MO.Count > m)
            // Цикл от выше взятой записи
            {
                // Запись в модель
                months1.Add(new Months()
                {
                    Id = Convert.ToInt32(MO[m].Id),
                    Month_Name = MO[m].Month_Name.ToString()
                });
                m++;
            }
            
            var In = db.Salaryes.FromSqlInterpolated($"SelectAllSalaryes").ToList();
            // Запрос на хранимую процедуру для взятия количества записей
            List<Salaryes> salaryes = new List<Salaryes>();
            int f = 0;
            while (In.Count > f)
            // Цикл от выше взятой записи
            {
                foreach (Employees val in employees1)
                // Берет запись из локальной переменной Сотрудник и записывает в новую локальную переменную
                {
                    foreach(Years val2 in years1)
                    // Берет запись из локальной переменной Год и записывает в новую локальную переменную
                    {
                        foreach (Months val3 in months1)
                        // Берет запись из локальной переменной Месяц и записывает в новую локальную переменную
                        {
                            if (val.Id == In[f].Employee && val2.Year_Name == In[f].Year && val3.Id == In[f].Month)
                            // Логическая переменная, которая проверяет на схожесть записей
                            {
                                employees = val;
                                years = val2;
                                months = val3;
                                salaryes.Add(new Salaryes()
                                // Запись в модель
                                {
                                    Id = Convert.ToInt32(In[f].Id),
                                    Year = Convert.ToInt32(In[f].Year),
                                    Month = Convert.ToInt32(In[f].Month),
                                    ParticipationInThePurchase = (short)Convert.ToInt32(In[f].ParticipationInThePurchase),
                                    ParticipationOnSale = (short)Convert.ToInt32(In[f].ParticipationOnSale),
                                    ParticipationOnProduction = (short)Convert.ToInt32(In[f].ParticipationOnProduction),
                                    TotalNumberOfParticipations=Convert.ToInt32(In[f].TotalNumberOfParticipations),
                                    Bonus = Convert.ToInt32(In[f].Bonus),
                                    Salary = Convert.ToInt32(In[f].Salary),
                                    TotalSum = (float)In[f].TotalSum,
                                    Boolean= (bool)In[f].Boolean,
                                    Year_NameNavigation = years,
                                    MonthNavigation = months,
                                    EmployeeNavigation=employees,
                                });
                            }
                        }
                    }
                }
                f++;
            }
            
            if(yearstring != 0 && monthstring!=0)
            // Логический оператор, который проверяет на использование фильтрации
            {
                var sal = _context.Salaryes.FromSqlInterpolated($"SelectYM @y={ yearstring}, @m={monthstring}").ToList();

                List<Salaryes> salaryes1 = new List<Salaryes>();
                ViewBag.Mas = sum;
                if (sal.Count==0)
                // Логический оператор, который проверяет на наличие записи в таблице "Зарплата"
                // Если запись по выбранной дате не имеет записи, то
                {
                    SqlParameter sqlParameterY = new SqlParameter("@Year", yearstring);
                    // Входной параметр год
                    SqlParameter sqlParameterM = new SqlParameter("@Month", monthstring);
                    // Входной параметр месяц
                    db.Database.ExecuteSqlInterpolated($"Salaryies @y={yearstring}, @m={monthstring}").ToString();
                    
                    // Запись в таблицу "Зарплата" по выбранной дате
                    return RedirectToAction("Index", new { yearstring = sqlParameterY, monthstring = sqlParameterM });
                }
                else
                // Иначе
                {
                    double summ = 0;
                    for(int j = 0; j < sal.Count; j++)
                    {
                        summ += sal[j].TotalSum;
                    }
                    ViewBag.Summa = summ;

                    int n = 0;
                    while (sal.Count > n)
                    {
                        foreach (Employees val in employees1)
                        {
                            foreach (Years val2 in years1)
                            {
                                foreach (Months val3 in months1)
                                {
                                    if (val.Id == sal[n].Employee && val2.Year_Name == sal[n].Year && val3.Id == sal[n].Month)
                                    {
                                        employees = val;
                                        years = val2;
                                        months = val3;
                                        salaryes1.Add(new Salaryes()
                                        {
                                            Id = Convert.ToInt32(sal[n].Id),
                                            Year = Convert.ToInt32(sal[n].Year),
                                            Month = Convert.ToInt32(sal[n].Month),
                                            ParticipationInThePurchase = (short)Convert.ToInt32(sal[n].ParticipationInThePurchase),
                                            ParticipationOnSale = (short)Convert.ToInt32(sal[n].ParticipationOnSale),
                                            ParticipationOnProduction = (short)Convert.ToInt32(sal[n].ParticipationOnProduction),
                                            TotalNumberOfParticipations = Convert.ToInt32(sal[n].TotalNumberOfParticipations),
                                            Bonus = Convert.ToInt32(sal[n].Bonus),
                                            Salary = Convert.ToInt32(sal[n].Salary),
                                            TotalSum = (float)sal[n].TotalSum,
                                            Boolean = (bool)sal[n].Boolean,
                                            Year_NameNavigation = years,
                                            MonthNavigation = months,
                                            EmployeeNavigation = employees,
                                        });
                                    }
                                }
                            }
                        }
                        n++;
                    }
                    return View(sal);
                }
            }
            else
            {
                ViewBag.Message = M;
                
                // Сообщение о каких-либо ошибках
                return View(salaryes);
            }
            ViewData["Yea"] = new SelectList(_context.Years, "Year_Name", "Year_Name");
            ViewData["Month"] = new SelectList(_context.Months, "Id", "Month_Name");
            ViewData["Employee"] = new SelectList(_context.Employees, "Id", "Fio");
        }

MSDB/Views/Salaryes/Create.cshtml
@model MSDB.Models.Salaryes

@{
    ViewData["Title"] = "Create";
}

<h1>Создать</h1>

<h4>Зарплата</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Year" class="control-label">Год</label>
                <select asp-for="Year" class="form-control" asp-items="ViewBag.Yea"></select>
            </div>
            <div class="form-group">
                <label asp-for="Month" class="control-label">Месяц</label>
                <select asp-for="Month" class="form-control" asp-items="ViewBag.Month"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад в список</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MSDB/Views/Salaryes/Delete.cshtml
@model MSDB.Models.Salaryes

@{
    ViewData["Title"] = "Delete";
}

<h1>Удалить</h1>

<h3>Вы действительно хотите удалить это?</h3>
<div>
    <h4>Salaryes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Month)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationInThePurchase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationInThePurchase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationOnSale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationOnSale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationOnProduction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationOnProduction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNumberOfParticipations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNumberOfParticipations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalSum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalSum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Boolean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Boolean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeNavigation.Id)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MSDB/Views/Salaryes/Details.cshtml
@model MSDB.Models.Salaryes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Salaryes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Month)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Month)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationInThePurchase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationInThePurchase)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationOnSale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationOnSale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ParticipationOnProduction)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ParticipationOnProduction)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNumberOfParticipations)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNumberOfParticipations)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Bonus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Bonus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalSum)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalSum)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Boolean)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Boolean)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EmployeeNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EmployeeNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MSDB/Views/Salaryes/Edit.cshtml
@model MSDB.Models.Salaryes

@{
    ViewData["Title"] = "Edit";
}

<h1>Изменение</h1>

<h4>Зарплата</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Year" class="control-label">Год</label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Month" class="control-label">Месяц</label>
                <input asp-for="Month" class="form-control" />
                <span asp-validation-for="Month" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Employee" class="control-label">Сотрудник</label>
                <select asp-for="Employee" class="form-control" asp-items="ViewBag.Employee"></select>
                <span asp-validation-for="Employee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParticipationInThePurchase" class="control-label">Участие в закупке</label>
                <input asp-for="ParticipationInThePurchase" class="form-control" />
                <span asp-validation-for="ParticipationInThePurchase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParticipationOnSale" class="control-label">Участие в продаже</label>
                <input asp-for="ParticipationOnSale" class="form-control" />
                <span asp-validation-for="ParticipationOnSale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ParticipationOnProduction" class="control-label">Участие в производстве</label>
                <input asp-for="ParticipationOnProduction" class="form-control" />
                <span asp-validation-for="ParticipationOnProduction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalNumberOfParticipations" class="control-label">Итого</label>
                <input asp-for="TotalNumberOfParticipations" class="form-control" />
                <span asp-validation-for="TotalNumberOfParticipations" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Bonus" class="control-label">Бонус</label>
                <input asp-for="Bonus" class="form-control" />
                <span asp-validation-for="Bonus" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Salary" class="control-label">Зарплата</label>
                <input asp-for="Salary" class="form-control" />
                <span asp-validation-for="Salary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalSum" class="control-label">Общая сумма</label>
                <input asp-for="TotalSum" class="form-control" />
                <span asp-validation-for="TotalSum" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Boolean" /> @Html.DisplayNameFor(model => model.Boolean)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Сохранить" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Назад в список</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MSDB/Views/Salaryes/Index.cshtml
@model IEnumerable<MSDB.Models.Salaryes>

@{
    ViewData["Title"] = "Index";
}

<h1>Зарплата</h1>
<form asp-controller="Salaryes" asp-action="Index" method="get">
    <p>
        <main class="container-fluid pt-3">
            <div class="d-flex justify-content-between">
                <div class="row g-3">
                    <div class="col-auto">
                        @Html.DropDownList("yearstring", ViewBag.Yea as SelectList, "Выберите год", new { @ID = "vee" })
                        @*<select class="form-control" aria-label="Default select example" name="yearString" value="@ViewBag.yearString">
            </select>*@
                    </div>
                    <div class="col-auto">
                        @Html.DropDownList("monthstring", ViewBag.Month as SelectList, "Выберите месяц", new { @ID = "vee" })
                        @*<select class="form-control" aria-label="Default select example" name="monthString" value="@ViewBag.monthString">
            </select>*@
                    </div>
                    <div class="col-auto">
                        <button type="submit" class="btn btn-dark" value="Calculate">Вывести</button>
                    </div>
                    <div class="col-auto">
                        <button type="submit" asp-action="IndexAdd" class="btn btn-dark">Выдать зарплату</button>
                    </div>
                    <div>
                        <input value="@ViewBag.Summa" />
                    </div>
                </div>
            </div>
            <p></p>
        </main>
    </p>
</form>
<h2>@ViewBag.Message</h2>
<p>
    <a asp-action="Create">Создать новый</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                <h6>Год</h6>
            </th>
            <th>
                <h6>Месяц</h6>
            </th>
            <th>
                <h6>Участие в закупке</h6>
            </th>
            <th>
                <h6>Участие в продаже</h6>
            </th>
            <th>
                <h6>Участие в производстве</h6>
            </th>
            <th>
                <h6>Общее кол участий</h6>
            </th>
            <th>
                <h6>Бонус</h6>
            </th>
            <th>
                <h6>Зарплата</h6>
            </th>
            <th>
                <h6>Общая сумма</h6>
            </th>
            <th>
                <h6>Выдача</h6>
            </th>
            <th>
                <h6>Сотрудники</h6>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Year_NameNavigation.Year_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.MonthNavigation.Month_Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParticipationInThePurchase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParticipationOnSale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ParticipationOnProduction)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalNumberOfParticipations)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Bonus)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalSum)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Boolean)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmployeeNavigation.Fio)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Изменить</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Удалить</a>
                </td>
            </tr>
            }
        </tbody>
</table>